/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.findlog;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import leitor.LeitorCSV;

/**
 *
 * @author 23162795
 */
public class NewJFrame extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acesso = new javax.swing.JButton();
        senha = new javax.swing.JTextField();
        usr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Senha:");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(670, 290, 70, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Usuário:");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(670, 210, 70, 25);

        acesso.setBorderPainted(false);
        acesso.setContentAreaFilled(false);
        acesso.setFocusPainted(false);
        acesso.setFocusable(false);
        acesso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(acesso);
        acesso.setBounds(737, 434, 70, 20);

        senha.setBackground(new java.awt.Color(217, 217, 217));
        senha.setForeground(new java.awt.Color(7, 7, 7));
        senha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        senha.setToolTipText("");
        senha.setActionCommand("<Not Set>");
        senha.setBorder(null);
        senha.setCaretColor(new java.awt.Color(7, 7, 7));
        senha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        senha.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        jLayeredPane1.add(senha);
        senha.setBounds(680, 330, 190, 30);

        usr.setBackground(new java.awt.Color(217, 217, 217));
        usr.setForeground(new java.awt.Color(7, 7, 7));
        usr.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usr.setToolTipText("");
        usr.setActionCommand("<Not Set>");
        usr.setBorder(null);
        usr.setCaretColor(new java.awt.Color(7, 7, 7));
        usr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        usr.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrActionPerformed(evt);
            }
        });
        jLayeredPane1.add(usr);
        usr.setBounds(680, 250, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\23162795\\Downloads\\Frame 3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessoActionPerformed
        Login login = new Login();
        
        String senhaText = senha.getText();
        String usuarioText = usr.getText();
        String  Dir = "C:\\Users\\23162795\\Downloads\\login.csv";
        
        LeitorCSV arq = new LeitorCSV();
      boolean a = arq.buscaLoginArquivoCsv(Dir,usuarioText,senhaText);
        if (a) {
           JOptionPane.showInputDialog("corretos"); 
        } else {
            JOptionPane.showInputDialog("Usúario e/ou senha incorretos");
        }
        
        
//        if (usuarioText != null && senhaText != null) {
//            login.setUsuario(usuarioText);
//            login.setSenha(senhaText);
//        } 
        
    }//GEN-LAST:event_acessoActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
    }//GEN-LAST:event_senhaActionPerformed

    private void usrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acesso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
